#Mysql database
mysql:
  enable: false #if this option equals false the plugin use YML database
  host: 127.0.0.1
  port: 3306
  username: root
  database:
  password:
  usessl: false
# BungeeCord Settings
bungeecord:
  enable: false #if this option equals true plugins will be use bungeecord mode if using this option you must enable mysql database
  lobby: lobby # the bungeecord lobby server name
  servers:
    # the bungeecord rooms
    - room1 # room server name
    - room2
    - room3
# Game settings
settings:
  imposter:
    count:
      '1':
        limit: 4
        count: 1
      '2':
        limit: 7
        count: 2
    killdistance: Short # Can be Short , Normal , Long
    impostervision: 1.25 # Can be 0.75 , 1 , 1.25 , 1.5 , 1.75 , 2 , 2.25 , 2.5
  emergency_per_user: 1
  voting_time: 120 # voting time to sec
  player_speed: 1 # Can be 1 (min) 1.25 , 1.5 , 1.75 , 2 (max)
  confirm_ejects: true # Confirm the vot
  show_votes: false
  tasks:
    common: 2 # min (1) max (3)
    long: # min (1) max (2)
    short: #min (2) max (4)
    visual: true # Show tasks res for other players
